from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Brand', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')), ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')), ('website', models.URLField(blank=True, verbose_name='Сайт')), ('description', models.TextField(blank=True, verbose_name='Описание')), ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип'))], options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды', 'ordering': ['name']}),
        migrations.CreateModel(name='Category', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')), ('description', models.TextField(blank=True, verbose_name='Описание')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'))], options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории', 'ordering': ['name']}),
        migrations.CreateModel(name='Customer', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('full_name', models.CharField(max_length=150, verbose_name='ФИО')), ('phone', models.CharField(max_length=30, verbose_name='Телефон')), ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')), ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')), ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'))], options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели', 'ordering': ['full_name']}),
        migrations.CreateModel(name='Supplier', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=150, verbose_name='Название')), ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Контактное лицо')), ('phone', models.CharField(max_length=30, verbose_name='Телефон')), ('email', models.EmailField(max_length=254, verbose_name='E-mail')), ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес'))], options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики', 'ordering': ['name']}),
        migrations.CreateModel(name='Product', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=150, verbose_name='Название')), ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')), ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')), ('description', models.TextField(blank=True, verbose_name='Описание')), ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотография')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')), ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.brand', verbose_name='Бренд')), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория')), ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.supplier', verbose_name='Поставщик'))], options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары', 'ordering': ['name']}),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')), ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')), ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')), ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer', verbose_name='Покупатель'))], options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы', 'ordering': ['-created_at']}),
        migrations.CreateModel(name='OrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')), ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа')), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product', verbose_name='Товар'))], options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'}),
        migrations.CreateModel(name='Review', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')), ('text', models.TextField(verbose_name='Текст отзыва')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')), ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.customer', verbose_name='Покупатель')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар'))], options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы', 'ordering': ['-created_at']}),
        migrations.AddConstraint(model_name='review', constraint=models.UniqueConstraint(fields=('product', 'customer'), name='unique_product_customer_review')),
    ]
